version: '3.7'

services:
  web:
    build: ../django-test-ci
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../django-test-ci/:/code/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
